<?php 
return [
    'APL_SALT' => 'uwa7caknczxbfue1x9rzhjsel2xx37yrbkjm2k5ga91rzoxe11', 
    'APL_ROOT_URL' => 'https://goldsvet.org/lic', 
    'APL_PRODUCT_ID' => 7, 
    'APL_DAYS' => 5, 
    'APL_STORAGE' => 'FILE', 
    'APL_DATABASE_TABLE' => 'user_data', 
    'APL_LICENSE_FILE_LOCATION' => '.licenseDK', 
    'APL_NOTIFICATION_NO_CONNECTION' => 'Can\'t connect to licensing server.', 
    'APL_NOTIFICATION_INVALID_RESPONSE' => 'Invalid server response.', 
    'APL_NOTIFICATION_DATABASE_WRITE_ERROR' => 'Can\'t write to database.', 
    'APL_NOTIFICATION_LICENSE_FILE_WRITE_ERROR' => 'Can\'t write to license file.', 
    'APL_NOTIFICATION_SCRIPT_ALREADY_INSTALLED' => 'Script is already installed (or database not empty.', 
    'APL_NOTIFICATION_LICENSE_CORRUPTED' => 'License is not installed yet or corrupted.', 
    'APL_NOTIFICATION_BYPASS_VERIFICATION' => 'No need to verify', 
    'APL_INCLUDE_KEY_CONFIG' => 'wi9qydosuimsnls5zoe5q298evkhim0ughx1w16qybs2fhlcpn', 
    'APL_ROOT_IP' => '', 
    'APL_DELETE_CANCELLED' => 'YES', 
    'APL_DELETE_CRACKED' => 'YES', 
    'APL_GOD_MODE' => 'YES', 
    'APL_CORE_NOTIFICATION_INVALID_SALT' => 'Configuration error: invalid or default encryption salt', 
    'APL_CORE_NOTIFICATION_INVALID_ROOT_URL' => 'Configuration error: invalid root URL of Auto PHP Licenser installation', 
    'APL_CORE_NOTIFICATION_INVALID_PRODUCT_ID' => 'Configuration error: invalid product ID', 
    'APL_CORE_NOTIFICATION_INVALID_VERIFICATION_PERIOD' => 'Configuration error: invalid license verification period', 
    'APL_CORE_NOTIFICATION_INVALID_STORAGE' => 'Configuration error: invalid license storage option', 
    'APL_CORE_NOTIFICATION_INVALID_TABLE' => 'Configuration error: invalid MySQL table name to store license signature', 
    'APL_CORE_NOTIFICATION_INVALID_LICENSE_FILE' => 'Configuration error: invalid license file location (or file not writable)', 
    'APL_CORE_NOTIFICATION_INVALID_ROOT_IP' => 'Configuration error: invalid IP address of your Auto PHP Licenser installation', 
    'APL_CORE_NOTIFICATION_INVALID_ROOT_NAMESERVERS' => 'Configuration error: invalid nameservers of your Auto PHP Licenser installation', 
    'APL_CORE_NOTIFICATION_INVALID_DNS' => 'License error: actual IP address and/or nameservers of your Auto PHP Licenser installation don\'t match specified IP address and/or nameservers', 
    'APL_DIRECTORY' => base_path()
];
